app = "$FLY_APP"
kill_signal = "SIGINT"
kill_timeout = 5

[metrics]
port = 9090
path = "/metrics"

[experimental]
  auto_rollback = true

[env]
CADDY_FRONTEND = "DISABLE_HTTPS"
LITESTREAM_REPLICA_URL = "DISABLED_I_KNOW_WHAT_IM_DOING"
PUBLIC_SERVER_URL = "$PUBLIC_SERVER_URL"
HEADSCALE_DNS_CONFIG_BASE_DOMAIN =  "$HEADSCALE_DNS_CONFIG_BASE_DOMAIN"

[[services]]
  internal_port = 8080
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[mounts]
source = "hs_data"
destination = "/data"
