name: Deployment Checker with Smoke Tests

permissions:
  contents: read

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      # Barebones, enough to get it up and listening
      LITESTREAM_REPLICA_URL: "DISABLED_I_KNOW_WHAT_IM_DOING"
      PUBLIC_SERVER_URL: "https://headscale.example.com"
      HEADSCALE_DNS_BASE_DOMAIN: "example.com"
      CADDY_FRONTEND: "DISABLE_HTTPS"
    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Run local-equivalent smoke test
        run: make smoke-test
